# Generated by Django 4.1.3 on 2022-11-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
    ]
